import { ProviderCategory, ProviderManifest } from "@revstackhq/providers-core";

export const manifest: ProviderManifest = {
  name: "Stripe",
  slug: "stripe",
  version: "1.0.0",
  categories: [
    ProviderCategory.Card,
    ProviderCategory.Wallet,
    ProviderCategory.BankTransfer,
  ],
  engine: {
    revstack: "^1.0.0",
    node: ">=18.0.0",
  },
  media: {
    icon: "https://cdn.jsdelivr.net/npm/@revstackhq/provider-stripe/assets/logo.svg",
    logo: "https://cdn.jsdelivr.net/npm/@revstackhq/provider-stripe/assets/logo.svg",
  },
  status: "beta",
  links: {
    dashboard: "https://dashboard.stripe.com",
    support: "https://support.stripe.com",
    pricing: "https://stripe.com/pricing",
    documentation: "https://docs.revstack.dev/providers/stripe",
    setupGuide: "https://docs.revstack.dev/providers/stripe/setup",
  },
  compliance: {
    actsAsMoR: false,
    calculatesTaxes: true,
    pciLevel: "Level 1",
  },
  hidden: false,
  pricing: {
    model: "transactional",
    fees: "2.9% + 30¢ per transaction",
  },
  localization: {
    customerCountries: ["*"],
    merchantCountries: [
      "US",
      "CA",
      "GB",
      "AU",
      "NZ",
      "IE",
      "FR",
      "DE",
      "IT",
      "ES",
      "NL",
      "BR",
      "MX",
      "SG",
      "JP",
      "AE",
    ],
    processingCurrencies: [
      "USD",
      "EUR",
      "GBP",
      "JPY",
      "CAD",
      "AUD",
      "CHF",
      "CNY",
      "HKD",
      "SGD",
      "NZD",
      "BRL",
      "MXN",
      "ARS",
      "CLP",
      "COP",
      "PEN",
      "UYU",
      "SEK",
      "NOK",
      "DKK",
      "PLN",
      "CZK",
      "HUF",
      "RON",
      "BGN",
      "TRY",
      "INR",
      "KRW",
      "THB",
      "MYR",
      "IDR",
      "PHP",
      "TWD",
      "AED",
      "SAR",
      "ILS",
      "ZAR",
      "NGN",
      "KES",
      "EGP",
    ],
    settlementCurrencies: [
      "USD",
      "EUR",
      "GBP",
      "CAD",
      "AUD",
      "JPY",
      "SGD",
      "BRL",
      "MXN",
    ],
  },
  supportedPaymentMethods: ["card", "wallet"],
  systemTraits: {
    hasNativeIdempotency: true,
    sandboxStrategy: "separate_credentials",
    rateLimits: {
      requestsPerSecond: 100,
    },
  },
  capabilities: {
    customers: {
      supported: true,
      features: {
        create: true,
        update: true,
        delete: true,
      },
    },
    checkout: {
      supported: true,
      strategy: "redirect",
    },
    payments: {
      supported: true,
      features: {
        capture: true,
        disputes: true,
        partialRefunds: true,
        refunds: true,
      },
    },
    subscriptions: {
      supported: true,
      mode: "native",
      features: {
        multiItem: true,
        cancellation: true,
        pause: true,
        resume: true,
        proration: true,
      },
    },
    webhooks: {
      supported: true,
      verification: "signature",
    },
    billing: {
      invoiceItems: true,
      invoices: true,
      metered: "invoiced",
      paymentLinks: true,
    },
    catalog: {
      syncStrategy: "inline",
    },
    promotions: {
      coupons: "native",
    },
  },
  author: "Revstack",
  description:
    "The global standard for payment processing and financial infrastructure.",
  sandboxAvailable: true,
  setup: {
    request: {
      apiKey: {
        label: "Secret Key",
        type: "password",
        secure: true,
        required: true,
        description: "Stripe Secret API Key",
        pattern: "^sk_(test|live)_[a-zA-Z0-9]+$",
        errorMessage: "Must start with sk_test_ or sk_live_",
      },
      useStripeTax: {
        label: "Enable Stripe Tax",
        type: "switch",
        secure: false,
        required: false,
        description:
          "Automatically calculate taxes using Stripe Tax. (Ensure it is configured in your Stripe Dashboard first).",
      },
    },
    response: {
      webhookEndpointId: {
        secure: false,
        description: "Endpoint ID for webhooks",
      },
      webhookSecret: {
        secure: true,
        description: "Webhook signing secret",
      },
      apiKey: {
        secure: true,
        description: "Stripe Secret API Key",
      },
      useStripeTax: {
        secure: false,
        description: "Flag indicating if Stripe Tax is enabled",
      },
    },
  },
  paginationType: "cursor",
};
