/**
 * Standardized ISO 4217 Currency Codes.
 * This list includes major global currencies.
 */
export const RevstackCurrencyMap = {
  USD: "USD",
  EUR: "EUR",
  GBP: "GBP",
  CAD: "CAD",
  AUD: "AUD",
  JPY: "JPY",
  CHF: "CHF",
  NZD: "NZD",
  SEK: "SEK",
  DKK: "DKK",
  NOK: "NOK",
  MXN: "MXN",
  BRL: "BRL",
  INR: "INR",
  SGD: "SGD",
  HKD: "HKD",
  TWD: "TWD",
  KRW: "KRW",
  THB: "THB",
  MYR: "MYR",
  PHP: "PHP",
  IDR: "IDR",
  VND: "VND",
  CZK: "CZK",
  PLN: "PLN",
  HUF: "HUF",
  RON: "RON",
  TRY: "TRY",
  ZAR: "ZAR",
  CLP: "CLP",
  COP: "COP",
  PEN: "PEN",
  UYU: "UYU",
  ARS: "ARS",
  BGN: "BGN",
  CNY: "CNY",
  RUB: "RUB",
  ILS: "ILS",
  AED: "AED",
  SAR: "SAR",
} as const;

export type RevstackCurrency = keyof typeof RevstackCurrencyMap;
