import { RevstackCurrency } from "@revstackhq/providers-core";

export const currencyMap: Record<string, RevstackCurrency> = {
  usd: "USD",
  eur: "EUR",
  gbp: "GBP",
  jpy: "JPY",
  aud: "AUD",
  cad: "CAD",
  chf: "CHF",
  cny: "CNY",
  hkd: "HKD",
  nzd: "NZD",
  sek: "SEK",
  krw: "KRW",
  sgd: "SGD",
  nok: "NOK",
  mxn: "MXN",
  inr: "INR",
  rub: "RUB",
  zar: "ZAR",
  try: "TRY",
  brl: "BRL",
  twd: "TWD",
  dkk: "DKK",
  pln: "PLN",
  thb: "THB",
  idr: "IDR",
  huf: "HUF",
  czk: "CZK",
  ils: "ILS",
  clp: "CLP",
  php: "PHP",
  aed: "AED",
  cop: "COP",
  sar: "SAR",
  myr: "MYR",
  ron: "RON",
  ars: "ARS",
  uyu: "UYU",
};
